export const products = [
  {
    id: 1,
    image: "/assets/sakarias-armchair.png",
    category: "Chair",
    name: "Sakarias Armchair",
    rating: 5,
    price: 392,
  },
  {
    id: 2,
    image: "/assets/balastar-chair.png",
    category: "Chair",
    name: "Baltsar Chair",
    rating: 4,
    price: 299,
  },
  {
    id: 3,
    image: "/assets/anjay-chair.png",
    category: "Chair",
    name: "Anjay Chair",
    rating: 5,
    price: 519,
  },
  {
    id: 4,
    image: "/assets/nyantuy-chair.png",
    category: "Chair",
    name: "Nyantuy Chair",
    rating: 4,
    price: 921,
  },

  {
    id: 5,
    image: "/assets/sakarias-armchair.png",
    name: "Sakarias Armchair",
    rating: 5,
    price: 342,
  },
  {
    id: 6,
    image: "/assets/balastar-chair.png",
    category: "Chair",
    name: "Baltsar Chair",
    rating: 4,
    price: 249,
  },

  {
    id: 7,
    image: "/assets/sofa-product.jpg",
    category: "Sofa",
    name: "Classic Chesterfield",
    rating: 5,
    price: 1350,
  },
  {
    id: 8,
    image: "/assets/sofa-product.jpg",
    category: "Sofa",
    name: "Scandinavian Daybed",
    rating: 4,
    price: 890,
  },
  {
    id: 9,
    image: "/assets/sofa-product.jpg",
    category: "Sofa",
    name: "L-Shape Sectional",
    rating: 4,
    price: 1600,
  },
  {
    id: 10,
    image: "/assets/sofa-product.jpg",
    category: "Sofa",
    name: "Reclining Sofa",
    rating: 4,
    price: 1200,
  },
  {
    id: 11,
    image: "/assets/sofa-product.jpg",
    category: "Sofa",
    name: "Small Loveseat",
    rating: 3,
    price: 550,
  },
  {
    id: 12,
    image: "/assets/sofa-product.jpg",
    category: "Sofa",
    name: "Tufted Velvet Couch",
    rating: 5,
    price: 1100,
  },
  {
    id: 19,
    image: "/assets/beds-product.jpg",
    category: "Beds",
    name: "Modern Floating Bed",
    rating: 5,
    price: 1300,
  },
  {
    id: 20,
    image: "/assets/beds-product.jpg",
    category: "Beds",
    name: "Rustic Farmhouse Bed",
    rating: 4,
    price: 1050,
  },
  {
    id: 21,
    image: "/assets/beds-product.jpg",
    category: "Beds",
    name: "Kids Novelty Bed",
    rating: 4,
    price: 450,
  },
  {
    id: 22,
    image: "/assets/beds-product.jpg",
    category: "Beds",
    name: "Adjustable Smart Bed",
    rating: 5,
    price: 2500,
  },
  {
    id: 23,
    image: "/assets/beds-product.jpg",
    category: "Beds",
    name: "Folding Guest Bed",
    rating: 3,
    price: 300,
  },
  {
    id: 24,
    image: "/assets/beds-product.jpg",
    category: "Beds",
    name: "Four-Poster Luxury Bed",
    rating: 5,
    price: 1800,
  },
  {
    id: 25,
    image: "/assets/lamp-product1.jpg",
    category: "Lamp",
    name: "Modern Desk Lamp",
    rating: 4,
    price: 75,
  },
  {
    id: 26,
    image: "/assets/lamp-product2.jpg",
    category: "Lamp",
    name: "Industrial Floor Lamp",
    rating: 5,
    price: 120,
  },
  {
    id: 27,
    image: "/assets/lamp-product3.jpg",
    category: "Lamp",
    name: "Bedside Table Lamp",
    rating: 4,
    price: 45,
  },
  {
    id: 28,
    image: "/assets/lamp-product4.jpg",
    category: "Lamp",
    name: "Decorative Pendant Light",
    rating: 5,
    price: 90,
  },
  {
    id: 29,
    image: "/assets/lamp-product5.jpg",
    category: "Lamp",
    name: "LED Strip Light Kit",
    rating: 3,
    price: 30,
  },
  {
    id: 30,
    image: "/assets/lamp-product6.jpg",
    category: "Lamp",
    name: "Smart RGB Floor Lamp",
    rating: 5,
    price: 150,
  },
];

export const categories = ["Chair", "Beds", "Sofa", "Lamp"];

export const testimonials = [
  {
    id: 1,
    name: "Bang Upin",
    title: "Pedagang Asongan",
    quote:
      "Terimakasih banyak, kini ruanganku menjadi lebih mewah dan terlihat mahal",
    rating: 5,
    profileImage: "/assets/tstmprof-1.png",
    backgroundImage: "/assets/tstmbg-1.jpg",
  },
  {
    id: 2,
    name: "Ibuk Sukijan",
    title: "Ibu Rumah Tangga",
    quote:
      "Makasih Panto, aku sekarang berasa tinggal di apartment karena barang-barang yang terlihat mewah",
    rating: 5,
    profileImage: "/assets/tstmprof-2.png",
    backgroundImage: "/assets/tstmbg-2.jpg",
  },
  {
    id: 3,
    name: "Mpok Ina",
    title: "Karyawan Swasta",
    quote: "Sangat terjangkau untuk kantong saya yang tidak terlalu banyak",
    rating: 5,
    profileImage: "/assets/tstmprof-3.png",
    backgroundImage: "/assets/tstmbg-3.jpg",
  },
  {
    id: 4,
    name: "Ibuk Sukijan",
    title: "Ibu Rumah Tangga",
    quote:
      "Makasih Panto, aku sekarang berasa tinggal di apartment karena barang-barang yang terlihat mewah",
    rating: 5,
    profileImage: "/assets/tstmprof-2.png",
    backgroundImage: "/assets/tstmbg-2.jpg",
  },
  {
    id: 5,
    name: "Mpok Ina",
    title: "Karyawan Swasta",
    quote: "Sangat terjangkau untuk kantong saya yang tidak terlalu banyak",
    rating: 5,
    profileImage: "/assets/tstmprof-3.png",
    backgroundImage: "/assets/tstmbg-3.jpg",
  },
];

export const features = [
  {
    title: "Luxury facilities",
    description:
      "The advantage of hiring a workspace with us is that givees you comfortable service and all-around facilities.",
    link: "#",
  },
  {
    title: "Affordable Price",
    description:
      "You can get a workspace of the highst quality at an affordable price and still enjoy the facilities that are oly here.",
    link: "#",
  },
  {
    title: "Many Choices",
    description:
      "We provide many unique work space choices so that you can choose the workspace to your liking.",
    link: "#",
  },
];
